# task and env
env:
  env_name: Isaac-Velocity-Flat-Digit-V3-v0
  num_envs: 1
  seed: 0


# collector
collector:
  frames_per_batch: 2048
  total_frames: 100_000_000

# logger
logger:
  backend: wandb
  project_name: torchrl_example_ppo
  group_name: null
  exp_name: IsaacLabDigit
  test_interval: 1_000_000
  num_test_episodes: 5
  video: False
  video_length: 200
  video_interval: 2000


# Optim
optim:
  lr: 3e-4
  weight_decay: 0.0
  anneal_lr: True

# loss
loss:
  gamma: 0.99
  mini_batch_size: 64
  ppo_epochs: 10
  gae_lambda: 0.95
  clip_epsilon: 0.2
  anneal_clip_epsilon: False
  critic_coef: 0.25
  entropy_coef: 0.0
  loss_critic_type: l2